import cv2
import matplotlib.pyplot as plt

image_1 = cv2.imread('1.jpg')
image_2 = cv2.imread('2.png')
img_1 = cv2.resize(image_1, (500, 500))
img_2 = cv2.resize(image_2, (500, 500))
add_ = img_1 + img_2
cv2.imshow("add_", add_)
cv2.waitKey(0)
sub_ = img_1 - img_2
cv2.imshow("sub_", sub_)
cv2.waitKey(0)
mult_ = cv2.divide(img_1, img_2)
cv2.imshow("mult_", mult_)
cv2.waitKey(0)
divi_ = cv2.divide(img_1, img_2)
cv2.imshow("divi_", divi_)
cv2.waitKey(0)
and_ = cv2.bitwise_and(img_1,img_2)
cv2.imshow("and_", and_)
cv2.waitKey(0)
or_ = cv2.bitwise_or(img_1,img_2)
cv2.imshow("or_", or_)
cv2.waitKey(0)
plt.figure(1)
plt.subplot(2,3,1)
plt.imshow(add_)
plt.subplot(2,3,2)
plt.imshow(sub_)
plt.subplot(2,3,3)
plt.imshow(mult_)
plt.subplot(2,3,4)
plt.imshow(divi_)
plt.subplot(2,3,5)
plt.imshow(and_)
plt.subplot(2,3,6)
plt.imshow(or_)
plt.show()